-- Allows developers to delete unredeemed promo codes they personally
-- generated by mistake. SECURITY DEFINER because the promo_codes table has no
-- DELETE policy and the only legitimate path is this constrained RPC.
--
-- Refuses if:
--   * the caller is not a developer (is_developer = false / NULL),
--   * the code doesn't exist,
--   * the caller did not generate the code, or
--   * the code has already been redeemed (redeemed_at IS NOT NULL).
-- Returns the deleted id on success so the action layer can confirm.

CREATE OR REPLACE FUNCTION public.delete_promo_code(p_id uuid)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_is_dev boolean;
  v_created_by uuid;
  v_redeemed_at timestamptz;
  v_deleted uuid;
BEGIN
  SELECT is_developer INTO v_is_dev FROM public.profiles WHERE id = auth.uid();
  IF v_is_dev IS NOT TRUE THEN
    RAISE EXCEPTION 'Only developers can delete promo codes' USING ERRCODE = '42501';
  END IF;

  SELECT created_by, redeemed_at INTO v_created_by, v_redeemed_at
  FROM public.promo_codes
  WHERE id = p_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Promo code not found' USING ERRCODE = 'P0002';
  END IF;
  IF v_created_by IS DISTINCT FROM auth.uid() THEN
    RAISE EXCEPTION 'Cannot delete another developer''s promo code' USING ERRCODE = '42501';
  END IF;
  IF v_redeemed_at IS NOT NULL THEN
    RAISE EXCEPTION 'Cannot delete a redeemed promo code' USING ERRCODE = '23514';
  END IF;

  DELETE FROM public.promo_codes WHERE id = p_id RETURNING id INTO v_deleted;
  RETURN v_deleted;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.delete_promo_code(uuid) TO authenticated;
